### ISSUE TITLE
Can still tab to content even after modal is closed

### ISSUE THREAD

**Issue by marlonmarcello** [wethegit/wtc-modal-view#10]
As we talked about @NicholasLancey we will need to:
1. on close move `this._content` to `this.wrapperOfContent`
2. on open move `this._content` to `this.modalContent`

**Comment by andrewrubin** [comment]
Looks good to me @NicholasLancey, thanks!

For context, @marlonmarcello, Nick and I chatted about how it might be  _too_ opinionated to add the `display: block` property directly inline on the modal element, onOpen. As in, maybe it should be a CSS class which the dev can change to whatever they need it to be (perhaps `display: flex`, for example). That said, it's highly unlikely that a developer will need something other than display block for a modal, so I think we should leave it as it is, for readability's sake.

**Comment by andrewrubin** [comment]
Fixed by #11
