### ISSUE TITLE
Adjust docs for clarity around setters (RFC)

### ISSUE THREAD

**Issue by andrewrubin** [wethegit/wtc-modal-view#13]
## Description
The generated docs pick up `closeButtonContent(content)` as a function which takes in a content param, but there's no documentation around the fact that it is a setter. Meaning, its usage is `closeButtonContent = yourContent`, not `closeButtonContent(yourContent)`.

## Solutions?
Maybe this is as easy as outlining this in the comments. Or is there a better way in JSDoc to deal with this sort of thing?

**Comment by marlonmarcello** [comment]
Good catch. Gonna have to dig into JSDoc Docs

**Comment by andrewrubin** [comment]
I spent some time today looking into this, but can't find a good solution. I'm happy to just update the docs to `Setter: description of setter` or something. Thoughts?

**Comment by marlonmarcello** [comment]
@andrewrubin let's do that.
