### ISSUE TITLE
Add delay for CSS className removal

### ISSUE THREAD

**Issue by andrewrubin** [wethegit/wtc-modal-view#15]
## Description
On close, all classes are instantly removed from the modal element. Specifically, `"modal--open"` is removed, which instantly triggers `display: none` on the `.modal__content` div. 

## Solutions
This behaviour is _fine_, but I suggest we do one of two things:
- Alter it, so that `.modal__content` doesn't get `display: none` until after the modal fully closes (in the existing setTimeout, allowing time for animation).
- OR
- Keep this behaviour, but move the `optionalClass` removal to inside the setTimeout, so that we can override this `display: block/none` behaviour for custom exit animations of specific types of modal content.

https://user-images.githubusercontent.com/30575213/107801143-90bcd500-6d14-11eb-8822-d68092e95f06.mp4

**Comment by liamegan** [comment]
I feel like the second behaviour is the safer option. Do you anticipate any issues with this?

**Comment by andrewrubin** [comment]
Agreed. Second option is definitely safer.

As far as I know, we don't often add custom "exit" animations, so I imagine it wouldn't matter. Famous last words, though. Let's just make sure everyone has a chance to confirm that assumption before making any moves 😄

**Comment by marlonmarcello** [comment]
@andrewrubin I am good with either, I do feel like #1 is more natural and kinda expected.
