### ISSUE TITLE
Remove focus style from `.modal__focus-start`

### ISSUE THREAD

**Issue by NicholasLancey** [wethegit/wtc-modal-view#6]
Do we need the focus style on this to be rendered? I feel I'm removing it more then I ever need it.  Surely the only focussable elements should be the close button, and the content? What d'you think?

I can demo to give more context if needed.

```
 .modal__focus-start {
  &:focus {
    box-shadow: none;
    outline: none;
  }
}
```

**Comment by andrewrubin** [comment]
This is a bit of a conversation to be had. The style should be removed, but I think its behaviour needs to change. `focus-start` should not be focused on modalOpen. I'll make a new issue for this. Explanation below.

**Comment by andrewrubin** [comment]
Knowbility gave us an audit once that said when a modal opens, we should query for the first element in the content, make it focusable, and then focus it.

That way, the `focus-start` element is only ever used for backwards-tabbing-away from the close button. It would  never be programmatically focused, as it currently is, on-open. Maintaining the current behaviour (aside from initially focusing it), whenever this element is user-focused, it's immediately focused away from, and sent to either the close button or the last focusable element in the modal's content. This specific behaviour prevents the outline style from ever showing, as you can see in the current implementation.

As long as we remove the `focus-start` from being focused initially (which we should), this outline issue is no longer an issue.

**Comment by andrewrubin** [comment]
Please see #7
