### ISSUE TITLE
Update focus behaviour per Knowbility audit

### ISSUE THREAD

**Issue by andrewrubin** [wethegit/wtc-modal-view#7]
# The problem
The `.modal__focus-start` element gets programmatically-focused when the modal opens, and this creates an issue where an invisible element is focused. This is potentially disorienting to a keyboard user.

# Discussion
Knowbility suggested that instead of focusing an invisible element when the modal opens, we should focus the first item in the modal's content… even if it's not a natively-focusable element. The reason for doing this as opposed to, say, focusing the close button on-open, is because it's nice to have screen readers announce what is now in view. While I agree, I think it might be better to just focus the modal content element itself (on open).

# Proposed changes
- On open, set user focus either the first item in the content (heading, paragraph; whatever it may be) OR the entire modal content div.
- Update the `.modal__focus-start` element to listen for a focus event. When fired, this should immediately shift the user's focus to the last focusable element in the modal's content. If there are no focusable items in the modal's content, it should shift focus back to the close button.

**Comment by marlonmarcello** [comment]
Please see #5 and https://github.com/wethegit/wtc-modal-view/pull/5/commits/b42c67c1d3d1171c1ad98430e58c954ebf01eaf0

**Comment by marlonmarcello** [comment]
Fixed with #5
